client/src/components/widgets/charts/MultiLinePlot.vue, client/src/graphs/svg/encodings.ts, client/src/graphs/svg/renderers/BioLocalRenderer.ts, client/src/graphs/svg/renderers/EpiRenderer.ts, client/src/services/DonuService.ts, client/src/store/modules/simulation.ts, client/src/utils/DonuUtil.ts, client/src/utils/FetchUtil.ts, client/src/utils/SVGUtil.js, client/src/views/GraphExperiment/GraphExperiment.vue, client/src/views/Simulation/Simulation.vue, client/src/views/Simulation/components/ParametersPanel.vue, client/src/views/Simulation/components/VariablePanel.vue
https://user-images.githubusercontent.com/14062458/121699083-9fd24a80-ca9c-11eb-9725-2a6a3bc4daab.mov
=> Save and reset simulation

client/src/components/widgets/charts/MultiLinePlot.vue, client/src/store/modules/simulation.ts, client/src/utils/DonuUtil.ts, client/src/views/Simulation/components/VariablesPanel.vue
- Refactor of simulation store (cleanup such as addition of missing types)
- Addition of result aggregation (using mean)
=> Run aggregation

client/src/views/Graphs/Graph.vue
**What**
- fix #210
**How**
- On `loadData()` fill the values for the nodes and edges.
=> Make the graph counter dynamic

client/src/graphs/svg/encodings.ts, client/src/graphs/svg/renderers/EpiRenderer.ts, client/src/views/Models/Model.vue, client/src/views/Models/components/Graphs/GlobalGraph.vue
**What**
- Added outline for selected nodes to make them visually distinguishable. 
- Renamed `showHighlight` and `hideHighlight` methods to make clearer distinction from highlighting neighborhood. 
**Testing**
- Select a model
- Select a specific node
=> Mark nodes selected in the graph

client/src/views/Graphs/Graph.vue, client/src/views/Graphs/components/DrilldownPanel/EdgePane.vue, client/src/views/Graphs/components/DrilldownPanel/NodePane.vue
**What**
- Support to select neighborhood relationships to add to the subgraph
https://user-images.githubusercontent.com/10552785/125485331-a89f788c-51f4-414f-9faa-464333c38156.mov
=> Add neighbors to subgraph

client/src/services/DonuService.ts, client/src/static/mockedDataDemo.ts, client/src/store/modules/simulation.ts, client/src/types/types.ts, client/src/types/typesDonu.ts, client/src/types/typesModel.ts, client/src/utils/DonuUtil.ts, client/src/views/Models/Model.vue, client/src/views/Simulation/Simulation.vue, client/src/views/Simulation/components/ModelSelector.vue, client/src/views/Simulation/components/ParametersPanel.vue, client/src/views/Simulation/components/VariablesPanel.vue
**What**
- To be able to work on #243 I need to implement the new DONU API
**How**
- Thanks to @adamocarolli Observable and Galois DONU documentation
- Rewrite some functions and types 
- Added some fields in the mock data
- Added VueX mutations to the simulation store, so it is easier to debug with the Vue.js Dev tool.
- Change how the _aggregate_ variables are stored, to be simpler.
**Testing**
- Try to run a simulation on any model and see if it behave as expected before Galois' update.
- Be careful that if you do not select a _Functional Network_ graph before opening a simulation, Donu API will always return the same simulation results regardless of parameters values.
=> Updated DONU API

client/src/graphs/svg/encodings.ts, client/src/graphs/svg/renderers/EpiRenderer.ts, client/src/store/modules/simulation.ts, client/src/types/types.ts, client/src/views/Models/components/Graphs/GlobalGraph.vue, client/src/views/Simulation/components/ModelPanel.vue, client/src/views/Simulation/components/ParametersPanel.vue, client/src/views/Simulation/components/VariablesPanel.vue
**What**
- Made counters for the variables panel consistent with the counters in the parameters panel
- Fixed issues with the highlighting of nodes in the Model panel. Double clicking adds/removes variables and parameters from the panels. 
- Commented out the tooltips until we fix them.
=> Various fixes for the model panel

client/src/components/widgets/charts/MultiLinePlot.vue
=> Change multiline plot interpolation to linear

client/src/components/widgets/charts/MultiLinePlot.vue, client/src/store/modules/simulation.ts, client/src/styles/overrides.css, client/src/views/Simulation/components/ParametersPanel.vue, client/src/views/Simulation/components/VariablesPanel.vue
Solves the following issues:
- #289 
- #292
- #295
- #303
- #304
- #314
=> Consolidated fixes 1

client/src/utils/FetchUtil.ts
Check by seeing if the knowledge cards view has been repaired.
=> Fix broken get util function

client/src/services/DonuService.ts
Donu API has resolved Algebraic Julia simulation. This PR removes the code involved in avoiding that error. 
- Remove hard-coded model simulation type in favour of inferred type.
- No special instructions.
=> [REFACTOR] Remove hard-coded model simulation type

client/src/graphs/svg/renderers/EpiRenderer.ts, client/src/store/modules/simulation.ts, client/src/types/types.ts, client/src/views/Models/components/Graphs/GlobalGraph.vue, client/src/views/Simulation/components/ModelPanel.vue, client/src/views/Simulation/components/ParametersPanel.vue, client/src/views/Simulation/components/VariablesPanel.vue
**What**
- fix #281 by removing the `hidden` property of parameters and variables and renaming `edited` property to `displayed`
- `displayed` makes more sense than `hidden` since it was the opposite meaning
**Testing**
- Select a model and open the simulation view 
- Add parameters using the plus sign and make sure the yellow dots appear in the Model Panel
- Remove parameters using the no icon and make sure the yellow dots disappear 
Screenshot:
Updated screenshot with highlight box:
=> Remove hidden property

client/src/components/Modal.vue, client/src/styles/aske.css, client/src/styles/tooltip.css, client/src/styles/ui.css, client/src/views/Simulation/Simulation.vue, client/src/views/Simulation/components/RunButton.vue
**What**
- fix #296 
**How**
- Remove the _dropdown_ element and use the _Modal_ component.
**Video**
https://user-images.githubusercontent.com/636801/128081253-9ac729e6-f31f-42f2-9296-f3162fba8a57.mov
=> Change from dropdown to modal box

client/src/components/widgets/charts/MultiLinePlot.vue, client/src/store/modules/simulation.ts, client/src/types/types.ts, client/src/views/Simulation/components/VariablesPanel.vue
Adds band to variable panel and fixes incorrect aggregate function (mean avg value calculated incorrect).
Note: when testing keep in mind that the bands are only enabled when there are more than 5 runs
Fixes #324
=> Variable band

client/src/graphs/svg/renderers/EpiRenderer.ts, client/src/main.ts, client/src/views/Models/Model.vue, client/src/views/Models/components/Graphs/GraphLegend.vue, client/src/views/Simulation/components/ModelPanel.vue
**What**
- fix #298
**How**
**Video**
https://user-images.githubusercontent.com/636801/128879241-174f3f29-76b3-44c2-a53e-f6eed35d7f88.mov
=> Models legend

client/src/components/widgets/LegendPanel.vue, client/src/styles/colours.css, client/src/views/Models/Model.vue, client/src/views/Models/components/Graphs/GraphLegend.vue, client/src/views/Simulation/Simulation.vue, client/src/views/Simulation/components/ModelPanel.vue, client/src/views/Simulation/components/SimulationLegend.vue
**What**
- fix #291 
**How**
- Separated the new model legends, into a legend panel to contains legends and a model legend.
- Created a new simulation legend for the runs.
**Videos**
https://user-images.githubusercontent.com/636801/128936065-5ea672b1-a93f-403e-adcb-cb4ee433cd31.mov
=> Simulation legend

client/src/views/Models/ModelsList.vue
**What**
- fix #321 
**How**
- Use the same behaviour as for the _Model_ view.
**Video**
https://user-images.githubusercontent.com/636801/129065796-c4cdc717-0e27-45d5-a953-3e8c6a47f2a4.mov
=> New searchbar in models view

client/src/graphs/svg/renderers/EpiRenderer.ts, client/src/services/DonuService.ts, client/src/static/gromets/emmaa_aggregated/marm_model_gromet_2021-06-28-17-07-14_graph_agg_rev_rategroups.json
Add marm model aggregation.
- Add aggregated marm model JSON to static file server
- Replace marm parsed graph representation with pre-aggregated representation 
- Lower edge opacity on larger models
- Here we perform offline aggregation of the marm model instead of modifying the Python code to Javascript and running in browser. Either option is valid, however, since the Python code had been unstable/changing I didn't want to add an extra dependency in translating it over and over again if we made another change.
- Scalable flow graphs is something that needs additional time investment. I think that we should start moving the renderer over to grafer for more performant large graph handling, however, we'll need to add an expand/collapse feature and a stable camera during expansion. The …
=> [FEATURE] Aggregate marm model

client/src/graphs/svg/renderers/EpiRenderer.ts, client/src/views/Models/components/Graphs/GlobalGraph.vue
**What**
- Marked container nodes as selected. Before only leaf nodes were marked as selected.
**Testing**
- Open a model.
- Select a container node. It should look selected (yellow outline)
=> Added selection of container nodes to the Models visualization

client/src/components/Counters.vue, client/src/views/Models/ModelsList.vue, client/src/views/Simulation/components/ModelPanel.vue
**What**
- fix #355 
**How**
- Add the modeling framework to the counter
**Screenshot**
=> Modeling framework in simulation

client/src/services/DonuService.ts
**What**
- Removing the hack I added to fetch the CHIME+ gromet PNC used for structural model comparison.
=> Remove Chime+ Gromet PNC to be fetched locally

client/src/services/DonuService.ts, client/src/store/modules/simulation.ts, client/src/types/types.ts, client/src/views/Comparison/Comparison.vue, client/src/views/Models/Model.vue, client/src/views/Simulation/Simulation.vue, client/src/views/Simulation/components/ModelPanel.vue
**What**
- fix #351 
**How**
- Update counters on the `Model` and `Comparison` views to behave like in the `Simulation` view.
- Initialize simulation parameters and variables for each visible models
**Video**
https://user-images.githubusercontent.com/636801/129627883-950bc1ef-c4a2-4213-9f65-f175f0f3151d.mov
=> Updated counters

client/src/views/Knowledge/DocsClusters/DocsClusters.vue, client/src/views/Knowledge/components/Settings.vue
=> Re-enable knowledge view switching buttons

client/src/components/Cards/Card.vue, client/src/utils/CosmosDataUtil.ts, client/src/views/Knowledge/DocsCards/DocsCards.vue, client/src/views/Knowledge/components/DrilldownPanel/EntitiesPane.vue, client/src/views/Knowledge/components/DrilldownPanel/KnowledgePreviewPane.vue, client/src/views/Knowledge/components/DrilldownPanel/ModelsPane.vue
**What**
- fix #310 
**How**
- Tidy up the component
- Added some conditional accessors for the _Drilldown panel_
- Updated how the list of author is displayed. But based on the data, I can't format it like `John A. Doe -> J.A. Doe`. There are too many cases of authors list and how they are formatted to clean them up without making mistakes.
**Testing**
Here is the ASKE-ID to reproduce Rosa's bug: `8467496e-3dfb-4efd-9061-433fef1b92de`
**Video**
https://user-images.githubusercontent.com/636801/129799105-48dc1308-50a9-4437-8038-a40202ae8cd7.mov
=> Knowledge cards subtitles

client/src/store/modules/simulation.ts, client/src/types/types.ts, client/src/views/Simulation/Simulation.vue, client/src/views/Simulation/components/ParametersPanel.vue
1. Updated how the parameter panel detect if a value is invalid or not.
2. Updated how the `Run` button is disabled based on the above.
=> fix error message with marm model

client/src/graphs/svg/elk/adapter.js
**What**
- Thanks to Dan. Chang for the pointer on this. Edges weren't placed properly for some of the gromets.
Before
After
=> Fix issue with edges being displaced for some gromets

client/src/graphs/svg/renderers/EpiRenderer.ts
=> Make nodes larger and fonts smaller

client/src/store/modules/simulation.ts
Trim observed data length to be only as long as predicted and compute error on trimmed. 
- Trim observed data length to be length of predicted if data length longer then predicted length
- Compute error using trimmed observed data length 
- Observed data trim is not updated when a simulation is run using different length parameters. Workaround is to reselect a dataset. In a subsequent PR @mj3cheun and I will go through these interaction problems to resolve 
- None
=> Sync observed data length with predicted

client/src/components/widgets/charts/MultiLinePlot.vue, client/src/utils/NumberUtil.ts
=> Add tooltip to multiline plot

client/src/views/Simulation/Simulation.vue, client/src/views/Simulation/components/ParametersPanel.vue, client/src/views/Simulation/components/VariablesPanel.vue
Modified parameters and variable panels of simulation view to use node selection system for parameter and variable highlighting
=> Parameter variable highlighting
