- client/src/views/Simulation/Simulation.vue
- client/src/views/Simulation/components/ParametersPanel.vue
- client/src/views/Simulation/components/VariablesPanel.vue
**What**
- Sorted parameter values in ascending order
- Sorted variables panel in ascending order
- I also cleaned up some unused code in the `Simulation` view that has been carried over from copying and pasting.
- BONUS: I also added the counter values for the variables panel. 
**How**
- Used the `orderBy` lodash function.
- For the variables counters, I mostly emulated how we do it for the parameters counter.
**Screenshot**
**Notes**
In the future, we might want to add support for the user to select the order criteria (descending, ascending, etc.)
**Testing**
- Select a model.
- Click on `Open Simulation View`
- Parameters and variables should be ordered in ascending order.
> Sort parameter values and variables in ascending order 

- client/package.json
- client/src/utils/BGraphQueryUtil.ts
- client/src/utils/BGraphUtil.ts
- client/src/utils/QueryFieldsUtil.ts
- client/src/views/Graphs/components/SearchBar.vue
- yarn.lock
Add path queries to the bio view. See attached screenshots for examples.
- Upgrade bgraph library from v0.1.0 to v0.2.0. See release notes for changes: https://github.com/uncharted-aske/bgraph/releases/tag/v0.2.0
- Add path query execution builder to bgraph utils. **See consideration.**
- Refactored edge/node/path cases into their own utility for code clarity and de-duplication.
- Handle the results of a path query different from the results of an edge/node query. In a path query the bgraph query results are flattened to include the underlying path present within the Gremlin's state. In an edge/node query the underlying Gremlin's path state is ignored.
- A path query clause is broken up into a pre- path clause and a -post path clause before running the path query builder function. This is …
> [FEATURE ] Add bio path query

- client/src/types/typesDonu.ts
- client/src/views/Simulation/components/ModelPanel.vue
- client/src/views/Simulation/components/ModelSelector.vue
Temporary fix addressing #228
Adds a small section to the models pane allowing the user to change which variables and parameters are hidden/visible. This is done to demonstrate the capability until a working model renderer is put into the simulate panel and the feature can be implemented for real.
Note that because of issues with accessing donu using the new gromet models, it will not be possible to test this PR unaltered. The PR was developed using an older version of the `main` branch. A small clip was made demonstrating the functionality to be added in this PR, PM me on slack for access to the clip due to github size constraints.
> Temporary models pane selector for variables and parameters

- client/src/components/SettingsBar.vue
- client/src/views/Simulation/components/VariablesPanel.vue
Fixes #230
Simple addition which adds a run counter to the variables panel. The light-mode mock up uses grey text, but since I didn't find that looked great on a dark theme, I went with making the text smaller to de-emphasize it while keeping the text colour the same as everything else. The other option is to keep the text the same size and colour as everything else which I think looks fine too. Thoughts?
Note: Again because of Donu difficulties, this will not work out-of-the-gate either if you wish to test it yourself. An easy way to rig it so that works is just to replace references to `getVariablesRunsCount` in the code with some integer.
> Add runs counter to the simulation variables panel

- client/src/graphs/svg/elk/adapter.js
- client/src/types/typesGraphs.ts
- client/src/views/Graphs/components/Graphs/LocalGraph.vue
- client/src/views/Models/Model.vue
- client/src/views/Models/components/Graphs/GlobalGraph.vue
- client/src/views/Models/components/Graphs/LocalGraph.vue
**What**
- Added `node-click` event for the `GlobalGraph.vue` in the Models view (for the demo in February) we were only allowing drilling down operations from the `LocalGraph` but that has been removed and now the split view is used for simulation. 
- Update local graph in the `Graphs` space that got outdated with the latest changes in the graph adapters.
**Screenshots**
**To test**
- Select the SIR model and click on a specific node using any of the modeling frameworks.
- The drilldown panel should open and show the node title, node type and data type. 
- The rest of collapsible panels are empty but we should be able to populate them with the new `metadata` we receive in GroMets.
> Hook up node click event for Global Graph in the Models view

- client/src/filters/CapitalizeFormatter.ts
- client/src/main.ts
- client/src/styles/aske.scss
- client/src/styles/metadata.scss
- client/src/types/typesGroMEt.ts
- client/src/views/Models/Model.vue
- client/src/views/Models/components/DrilldownPanel/MetadataPane.vue
- client/src/views/Models/components/MetadataPanel.vue
**What**
- Display the metadata provided by GroMET on a _Computational Model_.
**How** 
- Created a new Vue Filter to capitalize text;
- Separated the metadata styling out of the models' components into a separate stylesheet;
- Created a new GroMET interface to handle `CodeSpanReference` metadata type;
- Tidy up the _Models_ view metadata panes to be identical; and
- Clean unused code.
**Testing**
- Select and open a _Computational Model_ 
- Click on a node, either in _Petri Net Classic_ or _Functional Network_ modelling framework
- Make sure the `drilldown-panel` open on the right with the `metadata` pane open
- See if the *Code Reference* metadata and provenance are displayed like in the screenshot.
- If there is no metadata available, a message should be displayed
**Screenshot** …
> Metadata panel for model nodes

- client/src/components/Collapsible/CollapsibleItem.vue
- client/src/views/Graphs/Graph.vue
- client/src/views/Graphs/components/DrilldownPanel/NodePane.vue
Add in and out neighbour lists to the bio subgraph populated using bgraph for the currently selected node. Test by selecting different nodes in the bio subgraph.
Fixes #251
https://user-images.githubusercontent.com/14062458/125315658-55dfbd00-e305-11eb-8b17-b1e1bb00c8bb.mov
Notes: This PR changes how collapsible container and collapsible item works, by changing the CSS that fits these two components to the parent container. It is likely that this change will break existing components that use these two components. From a quick search, that appears to be only the edge panel which is currently disabled. I think we should just keep this in mind, keep an eye on it, and fix any potential problems when they appear. It will be good to double check that there are no other actively used components …
> Add neighbors to node panel of bio subgraph

- client/src/services/CosmosFetchService.ts
to test, do an edge DOI search for 10.1016/j.intimp.2020.107018 and then click on the green edge. there should not be any error.
> Fix error when cosmos artifacts is given a doi which does not exist

- client/src/styles/overrides.css
- client/src/views/Simulation/Simulation.vue
- client/src/views/Simulation/components/ModelPanel.vue
- client/src/views/Simulation/components/ParametersPanel.vue
- client/src/views/Simulation/components/RunButton.vue
- client/src/views/Simulation/components/VariablesPanel.vue
**What**
- Fix #256
- Other random UI changes to tidy up things
**How**
- Remove _Simulate_ button
- Remove all the _Settings_ buttons on the panels, are they have no uses
- Made the header control bar tidy with smaller buttons, better spacing
- Move the search bar to its own element that is made visible via the _Search_ toggle in the header
- Made the _Run_ fixed in width to avoid visual jump between _Run_ and _Auto_ labels
- Move the _Show/Hide all parameters_  buttons to the right of the panel to display the counter on the left like in the other panels.
**Video**
https://user-images.githubusercontent.com/636801/125829552-1bf89588-e343-4529-86fc-791fb3dcec10.mov
> Visual refinements in the Simulation space

- client/src/services/DonuService.ts
- client/src/static/mockedDataDemo.ts
- client/src/store/modules/model.ts
- client/src/types/typesDonu.ts
**What**
- filter out the non-GroMET models from the Donu APOI and the mocked data.
**How**
- use the current [Donu `model-def`](https://galoisinc.github.io/ASKE-E/donu.html#model-def) and only use `gromet-pnc` and `gromet-prt`.
> Make sure only GroMET models from Donu API are used on the HMI

- client/src/store/modules/simulation.ts
- client/src/views/Simulation/components/ParametersPanel.vue
**What**
GroMET PNC Donu API simulations were sending identical results.
**How**
By targeting the parameter `uid` instead of its `metadata.name` to send requests.
[This change was not documented](https://galoisinc.github.io/ASKE-E/donu.html#simulate---simulate-a-model), so thanks to @liunelson for reaching out to Galois.
**Screenshot**
> Donu fixes for PNC GroMET execution

- client/src/static/mockedDataDemo.ts
- Removed the `AlgebraicJulia.json` url error as soon as we open the Models view.
- Since Galois is still working on including and executing GrFNs, I just set the GrFN donu type to PNC in the meantime so we can switch to see the GrFN model. 
To test:
- As soon as you open the Models view, you shouldn't get an error anymore.
- Select the SIR model and switch to the Function Network modeling type, it should load normally.
> Fix of a couple of issues in the `main` branch

- client/src/views/Models/Model.vue
- client/src/views/Simulation/Simulation.vue
**What**
- After changing the search bar on the simulation view, the model view was not on par.
**How**
- Clean up the Model view code and implemented the same ideas.
- Random cleanup around.
**Testing**
- The search bar is now hidden behind a toggle button, and the open simulation button match the close button on the simulation view.
> Display the search bar on the model like on the simulation view.

- client/src/graphs/svg/renderers/EpiRenderer.ts
- client/src/views/Models/components/Graphs/GlobalGraph.vue
- client/src/views/Simulation/components/ModelPanel.vue
Double click nodes in the model representation panel to hide or show parameters and variables in the other panels. Solves #245
Check if PR #268 would impact this PR
Note: There is a limitation that when a node is toggled, then all parameters and variables with the label of the toggled node are toggled, which could be problematic if there is multiple parameters and variables with the same label.
https://user-images.githubusercontent.com/14062458/125829162-98332b76-c023-41a8-9bed-32f452445ccb.mov
> Added double click on model representation panel to hide/show parameters and variables in simulation view

- client/src/utils/SVGUtil.ts
- client/src/views/Simulation/components/ParametersPanel.vue
**What**
- Display scale on the parameter panel on the simulation view.
**How**
- Save the new roundup to pow10 range of the parameters.
- When adding the axis `<line>`, we also add two `<text>` labelled with min, max of the range.
- Group both the line and the labels in a group and translate the group as a whole.
- Made the label as dark and small as possible to maintain WCAG AA.
- Use scientific notation for big numbers.
**Screenshot**
> Add small label on the parameter axis

- client/src/views/Simulation/components/ParametersPanel.vue
**What**
- Move the parameter action button from the top-right to the middle-right
**How**
- Change the CSS grid template.
**Screenshot**
> Move the parameter action button

- client/package.json
- client/src/views/GraphExperiment/GraphExperiment.vue
- client/src/views/Models/components/Graphs/GlobalGraph.vue
- yarn.lock
Updated `svg-flowgraph` to latest version from 0.2.0 to 0.4.4 to take advantage of the interface change which removes render from `collapse` and `expand`, hence allowing either function to be called for a list of nodes to be collapsed/expanded without having to wait for the render for each to finish before the next can be called. This requires calling `yarn install` before running.
As this is a library update, its worth testing components using `svg-flowgraph` to ensure there aren't any bugs introduced.
Also note, there is a flash of fully expanded graph before the collapsed version is shown, I have not found a way to remove this.
https://user-images.githubusercontent.com/14062458/126690897-838eaee5-507c-4979-953f-822b6c00780c.mov
> Update svg-flowgraph to the latest version and remove collapse node animation

- client/src/services/DonuService.ts
- client/src/types/typesDonu.ts
Temporarily use GSL engine as default for petri net classic simulations as currently Donu API contains a bug when using Algebraic Julia as default.
- Add simulation engine types
- Override default simulation engine for petri net classic model types
- This is a temporary change while Donu is being fixed.
- I used the SimpleSIR model for testing.
> Use GSL engine for petri net classic simulation

- client/package.json
- client/src/utils/BGraphUtil.ts
- yarn.lock
Upgrade bgraph library from v0.2.0 to v0.3.2. (See release notes: https://github.com/uncharted-aske/bgraph/releases/tag/v0.3.2)
- Bump bgraph package to v0.3.2
- Modify path flattening to account for change in bgraph interface
- Performance improvements were not adequate for covid19 graph (only a ~2x improvement). There still remains a performance issue. Changes in the bgraph release improved path queries on sparse graphs with longer paths (typical of functional networks) much more then it did dense graphs with short paths (covid19).
- Ensure to `yarn install` before testing.
bgraph **v0.2.0** profiling over covid19 model using path query `Organisms -> small molecule`:
bgraph **v0.3.2** profiling over covid19 model using path query `Organisms -> small molecule`:
> Upgrade bgraph to v0.3.2

- client/src/graphs/svg/dagre/adapter.js
- client/src/graphs/svg/elk/adapter.js
- client/src/graphs/svg/encodings.ts
- client/src/graphs/svg/renderers/EpiRenderer.ts
- client/src/graphs/svg/util.js
- client/src/views/Models/components/Graphs/GlobalGraph.vue
- client/src/views/Simulation/components/ModelPanel.vue
**What**
- Clean up of unused colors and node types in `encodings.ts`
- Visual distinction between variable nodes (solid outline) and non-variable nodes (dashed outline)
- Visual distinction of initial conditions (ellipse)
- Added control for boxes so it is clearer they can be collapsed and expanded.
- Added marker for nodes added to the Parameters panel in the Simulation view (instead of using color)
- Removed unused code for tooltips.
**Testing**
- Open any of the models in the Models view (note that the current SIR PNC doesn't include any metadata, that's why nodes are dashed, we need to switch to use the right SIR PNC with actual metadata)
https://user-images.githubusercontent.com/10552785/127361364-377183ce-39ff-4351-944f-fbdbd03c0203.mov …
> Update GroMet visual encodings

- client/src/types/typesCosmos.ts
- client/src/types/typesGroMEt.ts
- client/src/utils/CosmosDataUtil.ts
- client/src/views/Models/Model.vue
- client/src/views/Models/components/DrilldownPanel/KnowledgePane.vue
note, when testing i noticed that xdd does not seem to have the aske-ids given by the grfn metadata in their system
> Use aske-id data in models view to populate knowlege drilldown panel with cosmos data

- client/src/services/DonuService.ts
- client/src/utils/FetchUtil.ts
The goal of this PR is to add memoization back to the donu simulate fetch. This will make the simulate view more responsive by eliminating most redundant API calls to donu and solves issue #297. To test, ensure the simulate page is working properly, one should notice a slight increase in responsiveness particularly with a large number of runs.
In order to address previous concerns with the current memoization system with high memory usage and memory leaks, the system was modified to track the size of each entry stored in bytes and limit the total amount of memory consumed by the store to a specified number of bytes. If the store fills up it will drop entries starting from the first one stored until there is sufficient space for a new entry to be stored.
The two parameters controlling the …
> Add in-memory size limit to fetch memoization system and implemented for donu service

- client/src/views/Simulation/Simulation.vue
- client/src/views/Simulation/components/ModelPanel.vue
- client/src/views/Simulation/components/ParametersPanel.vue
- client/src/views/Simulation/components/VariablesPanel.vue
**What**
- Added coordinated highlighting from Models panel to Vars/Params panel.
**How**
- Added border for parameters and variables containers if they have the same name than the selected node in the Model panel. Ideally, this should use the `uid` but it doesn't seem to match. NOTE: We probably want to double check that in the parser and adapt it. 
**Testing**
- Select a model and open the simulation view
- Add parameters and run the model.
- Select nodes from the Model visualization. The corresponding containers in the params/variable panels should get highlighted.
https://user-images.githubusercontent.com/10552785/127869001-fd07e022-c4de-45ff-b03b-2fd17c040560.mov
> Coordination between panels in the Simulation space

- client/src/graphs/svg/renderers/EpiRenderer.ts
- client/src/views/Simulation/components/ModelPanel.vue
**What?**
- Fix #328
- Rename `Highlighted` to `Displayed` to avoid confusion with the highlighted boxes on single click 
**How?**
- Checked the node arrays in ModelPanel and EpiRenderer to ensure the ids of displayed nodes were correct
- Updated d3 remove() to make yellow dots disappear
**Video**
https://user-images.githubusercontent.com/23723378/128226517-c3f03ff3-7d44-4031-aae1-8f52a3877ee6.mov
> Fix displayed markers

- client/src/types/typesGroMEt.ts
- client/src/views/Models/Model.vue
- client/src/views/Models/components/DrilldownPanel/MetadataPane.vue
**What**
- Added two additional types of metadata included in PNC EMMAA GroMETs (`IndraAgentReferenceSet` and `ReactionReference`)
- Using this metadata, we enable the ability to get agent references and pieces of evidence from EMMAA (similarly to how we do it for the Graphs).
**Testing**
- Select one of the two EMMAA gromets (MARM model or RAS model).I'd highly recommend you to test this out using the MARM model since the current RAS model is too big.
- Select a node from the model (edges don't include metadata for gromets)
NOTES: Testing might be annoying because you need to use the current EMMAA GroMEt visualizations, which take some time to load and are basically a hard ball, which makes difficult to select things. I also noticed, we don't seem to be getting DOIs from the EMMAA …
> Ability to show metadata for PNC EMMAA GroMEts

- client/src/components/Counters.vue
- client/src/services/DonuService.ts
- client/src/types/typesDonu.ts
- client/src/utils/QueryFieldsUtil.ts
- client/src/views/Models/ModelsList.vue
Add Donu text search capabilities to models list.
- Add Donu `query-models` service
- Add model's text search query pill type
- Add Text Pill to models list search bar
- React to filter changes modifying model list
- Going back from Model Simulation view does not keep filters in search bar.
- Model querying is slow. This is on the Donu side and may be a result of inefficient regex search.
- Search results are not great when little metadata is present.
- Regex search patterns can be used, ie. `*beta*`
> [FEATURE] Add text search query to model's list view

- client/src/components/Modals/ModalDocument.vue
- client/src/services/CosmosFetchService.ts
- client/src/utils/CosmosDataUtil.ts
- client/src/utils/QueryFieldsUtil.ts
- client/src/views/Knowledge/DocsCards/DocsCards.vue
- client/src/views/Models/Model.vue
- client/src/views/Models/components/DrilldownPanel/KnowledgePane.vue
- client/src/views/Models/components/MetadataPanel.vue
- client/src/views/Models/components/Modals/ModalDocMetadata.vue
The following changes were made in this PR (sorry the branch name is misleading)
- In the right side knowledge panel of the models view, allow aske-ids from both code collection and text reference metadata types to be used in generating the knowledge list. If both metadata types exist, then the results will be combined
- In the right side knowledge panel of the models view, if a knowledge title is clicked, then instead of opening an external link to the knowledge source, open a modal identical to those used in the docCards view showing the knowledge result metadata
- In the left side metadata panel of the models view, modify the documents section so that instead of a dropdown providing more metadata, a modal containing the metadata is opened instead
- In the dosCards view, searching by …
> Consolidated fixes

- client/src/store/modules/simulation.ts
- client/src/views/Simulation/components/ParametersPanel.vue
They were a simple issue from the DONU API that will send multiple parameters with same UID. Unfortunately they are not so _unique_. So we filter them out.
Also they will sometimes not provide a `metadata.name` for the parameters, so we use the UID in those occasions.
> Fix parameters panel error issue

- client/src/graphs/svg/renderers/EpiRenderer.ts
- client/src/store/modules/model.ts
- client/src/types/typesModel.ts
- client/src/utils/ModelUtil.ts
- client/src/views/Comparison/Comparison.vue
- client/src/views/Models/components/Graphs/GlobalGraph.vue
- client/src/views/Simulation/components/ModelPanel.vue
This PR accomplishes the following:
- Moves node selection from view files into the model store and created functions to calculate shared nodes and selected nodes given a specific model
- Adds highlight property to `EpiRenderer`
- Allows for (mostly) direct consumption of data provided by GTRI, Galois, etc. (Had to change the model names to match the model names fetched from donu)
- Supports one-to-many model comparison (demonstrated in the video)
- Full support for 2 model comparison with partial support for n model comparison (demonstrated in the video with rigged comparison input data) (full support requires model comparison data for each model to be compared and a function to combine multiple comparison data sources)
To test:
Click around the comparison view with the …
> Refactored model comparison system and added support for multi-model comparison linked node highlighting

- client/package.json
- client/src/types/typesGraphs.ts
- client/src/views/Models/components/Graphs/GlobalGraph.vue
- yarn.lock
Stabilize the pan/zoom of the model graph renderer on data/layout changes.
- Upgrade svg-flowgraph
- Add pan/zoom stabilize option to SVGRenderer's option type
- Set pan/zoom stabilization to true on EPIRenderer
- As the whole graph gets relayed out after each expansion sometimes the node expansion selected gets moved outside of the users field of view. This happens mostly with groups containing many nodes/incoming/outgoing edges 
- yarn install required
https://user-images.githubusercontent.com/15199528/129633793-3eb6f7e6-465e-44b5-85c5-3a7b2b6ee6b1.mov
> [FEATURE] Stabilize pan/zoom when expanding models

- client/src/utils/BGraphQueryUtil.ts
- client/src/utils/GraferUtil.ts
- client/src/utils/QueryFieldsUtil.ts
- client/src/views/Knowledge/DocsClusters/DocsClusters.vue
- client/src/views/Knowledge/components/Graphs/Grafer.vue
Add document title and DOI querying to document cluster view.
- Add document title query field and query function
- Add document DOI query field and query function
- Add search pills to document cluster view.
- Add document title search pill to document cluster view.
- Add foreground/background doc cluster grafer settings to enable query highlighting.
- Send events between knowledge grafer controller and document cluster view to enable query highlighting. Events added are (1) foreground original data (2) background original data (3) update/add layers (4) remove layers (5) grafer loaded (6) loaded grafer layers
- The document cluster grafer layer/layer data is sent back to the document view to be stored in memory. This is because when a query is made that view will then filter down the …
> [FEATURE] Add document cluster queries

- client/src/views/Simulation/components/ModelPanel.vue
**What**
- For some reason, we lost the coordination among panels (probably some regression issue)
**Testing**
- Open a model.
- Open the simulation space.
- Add parameters and run the model.
- Click on one of the nodes in the graph.
> Put coordination among panels back

- client/src/store/modules/model.ts
Fixes crash when attempting to open `CHIME_SIR` from a fresh state due to incorrect assumed graph type.
To test, from a fresh state, opening `SimpleSIR_metadata`, `CHIME_SIR`, and `SimpleChime+` model views should not result in any errors (either visible or in console). The correct graph type should be used for `CHIME_SIR` and `SimpleChime+`. Graph type switching should be unaffected in the `SimpleSIR_metadata` model.
> Fix incorrect graph type crash in models view

- client/src/views/Models/components/Graphs/GlobalGraph.vue
**What**
- Fixed small bug that kept the selection of consecutive boxes visible. 
https://user-images.githubusercontent.com/10552785/129955302-3f52750b-0301-47a3-b80c-544c3b408918.mov
> Fix selection of consecutive boxes 

- client/src/services/DonuService.ts
- client/src/types/typesDonu.ts
- client/src/utils/ErrorModelsUtil.ts
- client/src/utils/InterpolationModelsUtil.ts
Add mock Donu compute error endpoint. See Observable Notebook for understanding inputs/outputs: https://observablehq.com/d/f2195229ecf14e0c
- Add linear interpolation model
- Add L2 error model
- Add mocked Donu compute error function
- Endpoint reflects the proposed functionality layed out by @liunelson 
- The Observable notebook can be used for easier understanding. However you can also attach the compute error function to `window` with `window.computeDonuModelSimulationError = computeDonuModelSimulationError` and then test in browser. 
- https://observablehq.com/d/f2195229ecf14e0c
> Add mock Donu compute error endpoint

- client/package.json
**What**
- Downgraded svg-lib to previous version to fix https://github.com/uncharted-aske/HMI/issues/375
**Testing**
- Select a model
- Open the simulation panel
- The graph should still be visible right away.
> Downgrade SVG lib

- client/src/services/DonuService.ts
**What**
- HMS prefers to display this model in its de-aggregated version since it better conveys the linearity of the model. 
**Test**
- Select the COVID-19 gromet
> Remove aggregated version of the Covid19 gromet

- client/src/views/Simulation/components/ParametersPanel.vue
**What**
- Fix #396 
**How**
- Change the width for the parameter label to be **40%**, and update the graph to handle a percentage value instead of fix pixels
**Screenshot**
> Gives more space to the label

- client/package.json
- client/src/views/Models/components/Graphs/GlobalGraph.vue
**What**
- Collapsing models by default was causing the model to pan out of the Model panel when opening the Simulation view.
**How**
- Decided to remove the default collapsing of gromet GrFNs since it doesn't add much to the narrative of the demo. 
- I also put back the latest svg lib version.
https://user-images.githubusercontent.com/10552785/130469209-a8843f1a-788c-4c99-8ff7-b9255e23a6a9.mov
> Upgrade svg and uncollapse GrFN by default

- client/src/components/widgets/charts/MultiLinePlot.vue
**What**
- Big hack to increase the left margin for Variable plots in the Variables panel. 
- We probably should convert numbers to 10k format but I didn't get around it.
> Increased margin for Y-axis labels 

- client/src/graphs/svg/renderers/EpiRenderer.ts
- client/src/views/Models/components/Graphs/GlobalGraph.vue
**What**
- For the demo, we weren't really showing nested graphs so I disabled the automatic collapsing of boxes. However, CHIME models are highly nested so we required to put that back. Collapsing by default was the cause of the graph disappearing. 
- Addressed this issue by implementing a function that centers the graph.
- Put back the automatic collapsing
- Extra:  I also added the ability to drag nodes around that was already available in the SVG lib (although this is not perfect and it doesn't work so well with collapse and expand).
**Testing**
- Open the current CHIME SIR base model
- It should collapse top level boxes by default and get centered properly.
https://user-images.githubusercontent.com/10552785/130765533-95a3aba7-62cc-4be9-bfcb-d4b99ea7b856.mov
> Graph centering

- client/src/views/Models/components/Graphs/GlobalGraph.vue
**What**
- We collapse top-level boxes by default for GrFNs and for some reason, we need to re-render the layout when we do that. I moved the re-rendering out of the condition because I thought we would need to repeat it but we do.
**Test** 
- Open any GrFNs in the app.
> Fix issue where GrFNs couldn't get displayed
